### ISSUE TITLE
Убрать режим совместимости интерфейса

### ISSUE THREAD

**Issue by JohnyDeath** [dsdred/PAPI#1]
Предлагаю отключить проверку режима совместимости интерфейса.
Например, на типовую БП расширение без этого не натягивается
![image](https://github.com/user-attachments/assets/ee918006-39aa-4c03-a205-0de1e1782efa)

**Comment by dsdred** [comment]
Ок. В 0.9.3 уберу.

**Comment by dsdred** [comment]
В релизе 0.9.3 режим отключил.
