### ISSUE TITLE
Версия в описании и версия в "версии" не совпадают

### ISSUE THREAD

**Issue by JohnyDeath** [dsdred/PAPI#2]
Так и задумано?
![image](https://github.com/user-attachments/assets/2779d50b-c1d8-4864-b31e-1df8064bf521)

**Comment by dsdred** [comment]
Так и задумано. Я запланировал ряд изменений до версии 0.9.3 и в итоге их было очень много. Я решил побить на мелкие части, в данный момент доделываю последние изменения перед 0.9.3.
До 0.9.3 осталось сделать следующее:
1 Переделать содержание подсистем и поменять структуру подсистем.
2 Перенести функционал по чистке старых данных. (логи и прочие данные)
3 Сделать единую форму настроек.

**Comment by JohnyDeath** [comment]
@dsdred я к тому, что версию 0.9.2.6 можно было бы прописать и в графе "версия", чтобы не создавать путаницу и недопонимание.

**Comment by dsdred** [comment]
@JohnyDeath Я мысль понял. Хорошо, если это путает, тогда я сделаю промежуточную версию 0.9.2.7 и в "версии" сделаю такую же версию как в синониме. Выкачу промежуточный релиз на этой неделе.

**Comment by JohnyDeath** [comment]
@dsdred только ради этого выкатывать конечно же ничего не нужно. Просто в следующем релизе пусть будет одинаково
