### ISSUE TITLE
Вынести PAPI_ПодпискиНаСобытия.МассивВыполняемыхКоманд в модуль повторного использования

### ISSUE THREAD

**Issue by JohnyDeath** [dsdred/PAPI#4]
Вызов запроса в функции PAPI_ПодпискиНаСобытия.МассивВыполняемыхКоманд занимает значительное. Например, я сделал подписку на событие "ОбработкаПроверкиЗаполнения" для справочника договоров. И исполнение запроса в этой функции заняло 10% времени. Я считаю, что это достаточно много, если учесть, что почти все подписки выполняются в транзакции. + у меня в справочнике пока всего 2 подписки и только одна активная!
![image](https://github.com/user-attachments/assets/6d5fb5f0-690f-49a7-a4a3-2ce0e9475207)

Тем более, что результат этого метода всегда одинаковый, если все подписки уже устаканились. И меняется только при изменении подписки и/или алгоритма, который выбран внутри подписки. На это можно повесить сброс кэша. Также сделать кнопку принудительного сброса кэша администратором

Плюс, как видно из скрина, это место отработало 7 раз, несмотря на то, что у меня только одна подписка с одним объектом.
А метод вызывается для всех видов событий и для всех объектов.

**Comment by dsdred** [comment]
Данную проблему знаю, планировал оптимизацию в ближайших релизах.

**Comment by dsdred** [comment]
В 0.9.3 данный момент исправлен.
